grafana:
  restart: always
  volumes:
    - /app/metrics/grafana/lib:/var/lib/grafana
  ports:
    - "8012:3000"
  environment:
    - GF_SECURITY_ADMIN_USER
    - GF_SECURITY_ADMIN_PASSWORD

graphite:
  ports:
    - "8013:80"
    - "8001:2003"
    - "8002:2004"
  restart: always
  volumes:
    - /app/metrics/graphite/:/opt/graphite/storage
