influx-data:
  image: busybox
  #volumes:
  #  - $INFLUX_DB_DATAFOLDER:/data

influxdb:
  restart: always
  environment:
    - PRE_CREATE_DB
  volumes_from:
    - influx-data
  ports:
    - "8015:8083"
    - "8003:8086"

grafana-data:
  image: busybox
  volumes:
    - /app/metrics/grafana/lib:/var/lib/grafana

grafana:
  restart: always
  ports:
    - "8012:3000"
  environment:
    - GF_SECURITY_ADMIN_USER
    - GF_SECURITY_ADMIN_PASSWORD
volumes_from:
  - grafana-data
