influxdb:
  container_name: metrics_influxdb
  image: tutum/influxdb:0.10

grafana:
  image: grafana/grafana:2.6.0
  links:
    - influxdb
    - graphite

graphite:
  image: sitespeedio/graphite:0.9.14
