version: "3.1"

services:
  grafana:
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  graphite:
    ports:
      - "8000:80"
      - "8001:2003"
      - "8002:2004"

  loki:
    ports:
      - "3100:3100"
