version: "3.1"

services:
  grafana:
    image: grafana/grafana:6.7.4
    depends_on:
      - graphite
      - loki

  graphite:
    image: graphiteapp/graphite-statsd:1.1.7-6
  
  loki:
    image: grafana/loki:2.2.1
    command: -config.file=/etc/loki/local-config.yaml
