influxdb:
  restart: always
  environment:
    - PRE_CREATE_DB
  ports:
    - "8015:8083"
    - "8003:8086"

grafana-data:
  volumes:
    - /app/metrics/grafana/lib:/var/lib/grafana

grafana:
  restart: always
  ports:
    - "8012:3000"
  environment:
    - GF_SECURITY_ADMIN_USER
    - GF_SECURITY_ADMIN_PASSWORD

graphite:
  ports:
    - "8013:80"
    - "8001:2003"
    - "8002:2004"
  restart: always
