influx-data:
  image: tutum/influxdb:0.10
  entrypoint: /bin/true

influxdb:
  container_name: metrics_influxdb
  image: tutum/influxdb:0.10
  volumes_from:
    - influx-data

grafana-data:
  image: grafana/grafana:2.6.0
  entrypoint: /bin/true

grafana:
  image: grafana/grafana:2.6.0
  links:
    - influxdb
    - graphite
  volumes_from:
    - grafana-data

graphite-data:
  image: hopsoft/graphite-statsd:latest
  entrypoint: /bin/true

graphite:
  image: hopsoft/graphite-statsd:latest
  volumes_from:
    - graphite-data

cadvisor:
  image: google/cadvisor:v0.20.5
  links:
    - influxdb
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
  restart: always
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
