influxdb:
  container_name: metrics_influxdb
  image: tutum/influxdb:0.10

grafana:
  image: grafana/grafana:2.6.0
  links:
    - influxdb
    - graphite

graphite:
  image: sitespeedio/graphite:0.9.14

cadvisor:
  image: google/cadvisor:v0.20.5
  links:
    - influxdb
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
  restart: always
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
